"""migration 1

Revision ID: 1eabe93229e8
Revises: 
Create Date: 2025-02-26 17:24:15.643508

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1eabe93229e8'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('locations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('lot', sa.Float(), nullable=False),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_locations_id'), 'locations', ['id'], unique=False)
    op.create_index(op.f('ix_locations_name'), 'locations', ['name'], unique=False)
    op.create_table('weather_alerts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('msg', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_weather_alerts_id'), 'weather_alerts', ['id'], unique=False)
    op.create_table('weather_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('storm_warnings', sa.String(), nullable=False),
    sa.Column('temp', sa.Float(), nullable=False),
    sa.Column('humadity', sa.Float(), nullable=False),
    sa.Column('wind', sa.Float(), nullable=False),
    sa.Column('pressure', sa.Float(), nullable=False),
    sa.Column('discription', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_weather_data_id'), 'weather_data', ['id'], unique=False)
    op.create_table('weather_data_alerts',
    sa.Column('weather_data_id', sa.Integer(), nullable=True),
    sa.Column('weather_alert_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['weather_alert_id'], ['weather_alerts.id'], ),
    sa.ForeignKeyConstraint(['weather_data_id'], ['weather_data.id'], )
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('weather_data_alerts')
    op.drop_index(op.f('ix_weather_data_id'), table_name='weather_data')
    op.drop_table('weather_data')
    op.drop_index(op.f('ix_weather_alerts_id'), table_name='weather_alerts')
    op.drop_table('weather_alerts')
    op.drop_index(op.f('ix_locations_name'), table_name='locations')
    op.drop_index(op.f('ix_locations_id'), table_name='locations')
    op.drop_table('locations')
    # ### end Alembic commands ###
